---
# tasks file for k8s-installation-master
- name: Update all packages to their latest version
  apt:
    update_cache: yes
    force_apt_get: yes
# SET NODE NAME AS MASTER
- name: UPDATING HOSTNAME to master
  shell: 
    hostnamectl set-hostname  master && 
    bash

- name: adding a new line
  lineinfile:
    path: /etc/hosts
    line: '{{ private_ip_of_master_server }} master'

- name: Create a file containerd.conf in /etc/modules-load.d/
  file:
    path: /etc/modules-load.d/containerd.conf
    state: touch

- name: ADDING LINES to containerd.conf
  lineinfile:
    dest: /etc/modules-load.d/containerd.conf
    line: '{{ item }}'
  with_items:
    - 'overlay'
    - 'br_netfilter'
- name: Add the  module
  community.general.modprobe:
    name: '{{ item }}'
    state: present
  with_items:
    - 'overlay'
    - 'br_netfilter'

- name: Create a file kubernetes.conf in /etc/sysctl.d/
  file:
    path: /etc/sysctl.d/kubernetes.conf
    state: touch

- name: ADDING LINES to containerd.conf
  lineinfile:
    dest: /etc/sysctl.d/kubernetes.conf
    line: '{{ item }}'
  with_items:
    - 'net.bridge.bridge-nf-call-ip6tables = 1'
    - 'net.bridge.bridge-nf-call-iptables = 1'
    - 'net.ipv4.ip_forward = 1'

#- name: Just force systemd to reread configs
#  systemd_service:
#    daemon_reload: true
- name: Reload the system changes
  shell:
    sudo sysctl --system
- name: INSTALLING REQUIRED PACKAGES
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - curl
    - gnupg2
    - software-properties-common
    - apt-transport-https
    - ca-certificates

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable

- name: Update all packages to their latest version
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install containerd.io
  apt:
    pkg:
    - containerd.io
- name: Configure containerd 
  shell:
    containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
- name: Replace line in fiel /etc/containerd/config.toml
  lineinfile:
    path: /etc/containerd/config.toml
    regex: '^(.*)SystemdCgroup(.*)$'
    line: '            SystemdCgroup = true'
    backrefs: yes
- name: Start contanierd
  service:
   name: containerd
   state: restarted
   enabled: yes


- name: Add GPG key for k8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: Add Docker APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Update all packages to their latest version
  apt:
    update_cache: yes
    force_apt_get: yes
- name: INSTALLING REQUIRED PACKAGES
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
- name:  prevent the package from being automatically installed
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl

      #- name: showing output
      #  shell:
      #    uptime
      #  register:
      #    ps
      #  debug:
      #    var:
      #      ps.stdout_lines
- name : Runing kubeadm init
  shell:
    kubeadm init
- name: Create a directory if it does not exist
  file:
    path: /home/ubuntu/.kube/
    state: directory
- name: Create a config file in /home/ubuntu/.kube/
  file:
    path: /home/ubuntu/.kube/config
    state: touch
- name: Copy file from /etc/kubernetes/admin.conf to /home/ubuntu/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
